[project]
name = "stock-tax-cal"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.3.0",
    "streamlit>=1.46.0",
]
